name: Continuous Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy via SSH Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          cd final-project-team-7
          
          git reset --hard origin/master
          git pull
          
          docker container stop ml-client
          docker container rm ml-client
          docker image rm final-project-team-7-ml-client
          
          docker container stop web-client
          docker container rm web-client
          docker image rm final-project-team-7-web-client
          
          docker compose up --build --detach